<?php
    session_start();
    unset($_SESSION['user_admin']);
    unset($_SESSION['user_email']);
    unset($_SESSION['user_name']);
?>
 <script>
    alert("登出成功");
    parent.location.href='index.php';
</script>